version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: angeles
      POSTGRES_DB: puppy_tail
      POSTGRES_PASSWORD: 1234

  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    environment:
      - BACKEND_URL=http://back:8000
      - FRONTEND_URL=http://localhost
      - CLIENT_ID="AWsYLI9Dc8AbZPf_KLxEifhBS9lEWCOZuK9UjzFoFOdqz5tcaa8PLseePMBUvm_sPjrofRR5nW1aLEKB"
      - APP_SECRET="EGZ7-LqIjswMMEZ_m6N1L6-t7Yj_Va1GHDUlYuYCZXMZnl4nQNozBqotjIHBDj2WVMSBNk9cQJacOFBI"
      - DATABASE_URL=postgres://angeles:1234@db:5432/puppy_tail
    ports:
      - "81:8000"
    depends_on:
      - db

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
